import { environment } from '@/helpers/environment'
import { logError } from '@/helpers/logger'
import { User } from '@/types/modules'
import { ApolloError } from 'apollo-server-core'
import nodemailer from 'nodemailer'
import URL from 'url-parse'
import forgotPassword from '@extensions/mail-service/email-templates/forgot-password'
import SendGrid from '@sendgrid/mail'
interface GenerateEmailLink {
  email: string
  token: string
  BASE_URL: string
}

interface SendEmail {
  to: string
  template: string
  subject: string
  variables?: any
}

interface MailOptions {
  from: any
  to: any
  subject: any
  html: any
}

interface SelectTemplate {
  template: string
  variables?: any
}

const generateEmailLink = ({ email, token, BASE_URL }: GenerateEmailLink) => {
  const url = BASE_URL + '/reset/?token=' + token
  return URL(url).href
}

const selectTemplate = ({ template, variables }: SelectTemplate) => {
  switch (template) {
    case 'forgot-password':
      // variables.link = generateEmailLink({
      //   email: variables.email,
      //   token: variables.token,
      //   BASE_URL: variables.BASE_URL
      // })
      // variables.code = variables.token
      return forgotPassword(variables)
  }
}

export default async ({ to, subject, template, variables }: SendEmail) => {
  new Promise((resolve, reject) => {
    // create message
    var mailOptions: MailOptions = {
      from: `"${process.env.APP_NAME}" <info@contentre.io>`,
      to,
      subject,
      html: selectTemplate({ template, variables })
    }

    // if (environment.mail?.type === 'send') {
    //   SendGrid.setApiKey(environment.mail?.sendAPIKey!)
    //   console.log('here')
    //   SendGrid.send(mailOptions).then(
    //     (info) => {
    //       console.error(info)
    //       resolve(info)
    //     },
    //     (error) => {
    //       console.error(error)

    //       if (error.response) {
    //         console.error(error.response.body)
    //         reject(new ApolloError(error.response.body))
    //       }
    //     }
    //   )

    //   return
    // }

    // if (environment.context.includes('DEVELOP')) {
    const transporter = nodemailer.createTransport({
      host: environment.mail?.host || 'smtp.mailtrap.io',
      port: environment.mail?.port || 2525,
      auth: {
        user: environment.mail?.username || '1a2b3c4d5e6f7g', //generated by Mailtrap
        pass: environment.mail?.password || '1a2b3c4d5e6f7g' //generated by Mailtrap
      }
    })

    transporter.sendMail(mailOptions, (error, info) => {
      if (error) {
        console.log(error)
        logError('sendEmail %o', { mailOptions, error })
        reject(new ApolloError('try email again later', '500', error))
        return
      }

      console.log(info)
      resolve(info)
    })
    // }
  })
}
