-- CreateEnum
CREATE TYPE "Status" AS ENUM ('ACTIVE', 'INACTIVE');

-- AlterTable
ALTER TABLE "Client" ADD COLUMN  IF NOT EXISTS   "status" "Status" NOT NULL DEFAULT E'ACTIVE';

-- AlterTable
ALTER TABLE "Content" ADD COLUMN  IF NOT EXISTS   "bookmark" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN  IF NOT EXISTS   "favourite" BOOLEAN NOT NULL DEFAULT false;
